---
# defaults file for web

# Composer
composer_self_update: no
composer_path: '/usr/local/bin'

# PHP
php_ini_settings: []
php_fpm_socket: /var/run/php5-fpm.sock
php_fpm_settings: []

# PHP Extensions
php_extensions: []

# PHP Third Party Extensions
php_thirdparty_newrelic: no
